// Egypt governorate -> cities/markaz mapping
// Used by the public job application form to render a dependent city dropdown
// based on the selected governorate.

export interface CityOption {
  value: string;
  label_en: string;
  label_ar: string;
}

export const EGYPT_CITIES: Record<string, CityOption[]> = {
  cairo: [
    { value: "nasr_city",       label_en: "Nasr City",          label_ar: "مدينة نصر" },
    { value: "heliopolis",      label_en: "Heliopolis",         label_ar: "مصر الجديدة" },
    { value: "maadi",           label_en: "Maadi",              label_ar: "المعادي" },
    { value: "downtown",        label_en: "Downtown",           label_ar: "وسط البلد" },
    { value: "shubra",          label_en: "Shubra",             label_ar: "شبرا" },
    { value: "el_marg",         label_en: "El Marg",            label_ar: "المرج" },
    { value: "ain_shams",       label_en: "Ain Shams",          label_ar: "عين شمس" },
    { value: "el_matareya",     label_en: "El Matareya",        label_ar: "المطرية" },
    { value: "el_zaytoun",      label_en: "El Zaytoun",         label_ar: "الزيتون" },
    { value: "el_zawya",        label_en: "El Zawya El Hamra",  label_ar: "الزاوية الحمراء" },
    { value: "el_salam",        label_en: "El Salam",           label_ar: "السلام" },
    { value: "el_nozha",        label_en: "El Nozha",           label_ar: "النزهة" },
    { value: "helwan",          label_en: "Helwan",             label_ar: "حلوان" },
    { value: "el_basatin",      label_en: "El Basatin",         label_ar: "البساتين" },
    { value: "tora",            label_en: "Tora",               label_ar: "طرة" },
    { value: "fifth_settlement", label_en: "Fifth Settlement",  label_ar: "التجمع الخامس" },
    { value: "rehab",           label_en: "Rehab",              label_ar: "الرحاب" },
    { value: "madinaty",        label_en: "Madinaty",           label_ar: "مدينتي" },
    { value: "new_cairo",       label_en: "New Cairo",          label_ar: "القاهرة الجديدة" },
    { value: "obour",           label_en: "Obour",              label_ar: "العبور" },
    { value: "shorouk",         label_en: "Shorouk",            label_ar: "الشروق" },
    { value: "badr",            label_en: "Badr",               label_ar: "بدر" },
    { value: "el_mokattam",     label_en: "El Mokattam",        label_ar: "المقطم" },
  ],
  giza: [
    { value: "giza_city",       label_en: "Giza City",          label_ar: "الجيزة" },
    { value: "dokki",           label_en: "Dokki",              label_ar: "الدقي" },
    { value: "agouza",          label_en: "Agouza",             label_ar: "العجوزة" },
    { value: "mohandessin",     label_en: "Mohandessin",        label_ar: "المهندسين" },
    { value: "haram",           label_en: "Haram",              label_ar: "الهرم" },
    { value: "faisal",          label_en: "Faisal",             label_ar: "فيصل" },
    { value: "imbaba",          label_en: "Imbaba",             label_ar: "إمبابة" },
    { value: "boulaq",          label_en: "Boulaq El Dakrour",  label_ar: "بولاق الدكرور" },
    { value: "sixth_october",   label_en: "6th of October",     label_ar: "السادس من أكتوبر" },
    { value: "sheikh_zayed",    label_en: "Sheikh Zayed",       label_ar: "الشيخ زايد" },
    { value: "saft_el_laban",   label_en: "Saft El Laban",      label_ar: "صفط اللبن" },
    { value: "warraq",          label_en: "Warraq",             label_ar: "الوراق" },
    { value: "ayyat",           label_en: "Ayyat",              label_ar: "العياط" },
    { value: "badrasheen",      label_en: "Badrasheen",         label_ar: "البدرشين" },
    { value: "saqqara",         label_en: "Saqqara",            label_ar: "سقارة" },
    { value: "atfih",           label_en: "Atfih",              label_ar: "أطفيح" },
    { value: "wahat_bahareya",  label_en: "Wahat Bahareya",     label_ar: "الواحات البحرية" },
  ],
  alexandria: [
    { value: "montaza",         label_en: "Montaza",            label_ar: "المنتزه" },
    { value: "raml",            label_en: "Raml",               label_ar: "الرمل" },
    { value: "wasat",           label_en: "Wasat",              label_ar: "وسط" },
    { value: "gomrok",          label_en: "Gomrok",             label_ar: "الجمرك" },
    { value: "agamy",           label_en: "Agamy",              label_ar: "العجمي" },
    { value: "amreya",          label_en: "Amreya",             label_ar: "العامرية" },
    { value: "dekheila",        label_en: "Dekheila",           label_ar: "الدخيلة" },
    { value: "borg_arab",       label_en: "Borg El Arab",       label_ar: "برج العرب" },
    { value: "sidi_gaber",      label_en: "Sidi Gaber",         label_ar: "سيدي جابر" },
    { value: "stanley",         label_en: "Stanley",            label_ar: "ستانلي" },
    { value: "smouha",          label_en: "Smouha",             label_ar: "سموحة" },
    { value: "miami",           label_en: "Miami",              label_ar: "ميامي" },
  ],
  qalyubia: [
    { value: "banha",           label_en: "Banha",              label_ar: "بنها" },
    { value: "qalyub",          label_en: "Qalyub",             label_ar: "قليوب" },
    { value: "shubra_el_kheima", label_en: "Shubra El Kheima",  label_ar: "شبرا الخيمة" },
    { value: "khanka",          label_en: "Khanka",             label_ar: "الخانكة" },
    { value: "qaha",            label_en: "Qaha",               label_ar: "قها" },
    { value: "kafr_shokr",      label_en: "Kafr Shokr",         label_ar: "كفر شكر" },
    { value: "tukh",            label_en: "Tukh",               label_ar: "طوخ" },
    { value: "qanater",         label_en: "El Qanater",         label_ar: "القناطر الخيرية" },
    { value: "obour_qalyubia",  label_en: "Obour",              label_ar: "العبور" },
  ],
  sharqia: [
    { value: "zagazig",         label_en: "Zagazig",            label_ar: "الزقازيق" },
    { value: "10th_ramadan",    label_en: "10th of Ramadan",    label_ar: "العاشر من رمضان" },
    { value: "belbeis",         label_en: "Belbeis",            label_ar: "بلبيس" },
    { value: "minya_qamh",      label_en: "Minya El Qamh",      label_ar: "منيا القمح" },
    { value: "abou_hammad",     label_en: "Abou Hammad",        label_ar: "أبو حماد" },
    { value: "faqous",          label_en: "Faqous",             label_ar: "فاقوس" },
    { value: "hosseinia",       label_en: "El Hosseinia",       label_ar: "الحسينية" },
    { value: "kafr_saqr",       label_en: "Kafr Saqr",          label_ar: "كفر صقر" },
    { value: "salhia",          label_en: "Salhia El Gedida",   label_ar: "الصالحية الجديدة" },
    { value: "abou_kebir",      label_en: "Abou Kebir",         label_ar: "أبو كبير" },
    { value: "deyrb_negm",      label_en: "Deyrb Negm",         label_ar: "ديرب نجم" },
    { value: "ibrahimiyah",     label_en: "Ibrahimiyah",        label_ar: "الإبراهيمية" },
    { value: "qaneyat",         label_en: "Qaneyat",            label_ar: "القنايات" },
    { value: "san_el_hagar",    label_en: "San El Hagar",       label_ar: "صان الحجر" },
  ],
  dakahlia: [
    { value: "mansoura",        label_en: "Mansoura",           label_ar: "المنصورة" },
    { value: "talkha",          label_en: "Talkha",             label_ar: "طلخا" },
    { value: "mit_ghamr",       label_en: "Mit Ghamr",          label_ar: "ميت غمر" },
    { value: "aga",             label_en: "Aga",                label_ar: "أجا" },
    { value: "sherbin",         label_en: "Sherbin",            label_ar: "شربين" },
    { value: "manzala",         label_en: "Manzala",            label_ar: "المنزلة" },
    { value: "dekernes",        label_en: "Dekernes",           label_ar: "دكرنس" },
    { value: "belqas",          label_en: "Belqas",             label_ar: "بلقاس" },
    { value: "menyet_nasr",     label_en: "Menyet El Nasr",     label_ar: "منية النصر" },
    { value: "sinbillawein",    label_en: "Sinbillawein",       label_ar: "السنبلاوين" },
    { value: "gamalia",         label_en: "Gamalia",            label_ar: "الجمالية" },
    { value: "matareya_dak",    label_en: "Matareya",           label_ar: "المطرية" },
    { value: "nabaroh",         label_en: "Nabaroh",            label_ar: "نبروه" },
    { value: "mahala",          label_en: "Mahala Damana",      label_ar: "محلة دمنة" },
  ],
  gharbia: [
    { value: "tanta",           label_en: "Tanta",              label_ar: "طنطا" },
    { value: "mahalla",         label_en: "El Mahalla El Kubra", label_ar: "المحلة الكبرى" },
    { value: "kafr_zayat",      label_en: "Kafr El Zayat",      label_ar: "كفر الزيات" },
    { value: "zifta",           label_en: "Zifta",              label_ar: "زفتى" },
    { value: "samanoud",        label_en: "Samanoud",           label_ar: "سمنود" },
    { value: "santa",           label_en: "Santa",              label_ar: "السنطة" },
    { value: "qutour",          label_en: "Qutour",             label_ar: "قطور" },
    { value: "basyoun",         label_en: "Basyoun",            label_ar: "بسيون" },
  ],
  menoufia: [
    { value: "shibin_kom",      label_en: "Shibin El Kom",      label_ar: "شبين الكوم" },
    { value: "menouf",          label_en: "Menouf",             label_ar: "منوف" },
    { value: "sadat",           label_en: "Sadat City",         label_ar: "مدينة السادات" },
    { value: "ashmoun",         label_en: "Ashmoun",            label_ar: "أشمون" },
    { value: "berkat_sabaa",    label_en: "Berkat El Sabaa",    label_ar: "بركة السبع" },
    { value: "quesna",          label_en: "Quesna",             label_ar: "قويسنا" },
    { value: "tala",            label_en: "Tala",               label_ar: "تلا" },
    { value: "el_bagour",       label_en: "El Bagour",          label_ar: "الباجور" },
    { value: "el_shohada",      label_en: "El Shohada",         label_ar: "الشهداء" },
  ],
  beheira: [
    { value: "damanhour",       label_en: "Damanhour",          label_ar: "دمنهور" },
    { value: "kafr_dawar",      label_en: "Kafr El Dawar",      label_ar: "كفر الدوار" },
    { value: "rashid",          label_en: "Rashid",             label_ar: "رشيد" },
    { value: "edku",            label_en: "Edku",               label_ar: "إدكو" },
    { value: "abou_homos",      label_en: "Abou Homos",         label_ar: "أبو حمص" },
    { value: "delengat",        label_en: "El Delengat",        label_ar: "الدلنجات" },
    { value: "mahmoudiyah",     label_en: "Mahmoudiyah",        label_ar: "المحمودية" },
    { value: "rahmaniyah",      label_en: "Rahmaniyah",         label_ar: "الرحمانية" },
    { value: "etay_baroud",     label_en: "Etay El Baroud",     label_ar: "إيتاي البارود" },
    { value: "houch_eissa",     label_en: "Houch Eissa",        label_ar: "حوش عيسى" },
    { value: "shubrakhit",      label_en: "Shubrakhit",         label_ar: "شبراخيت" },
    { value: "kom_hamada",      label_en: "Kom Hamada",         label_ar: "كوم حمادة" },
    { value: "badr_beheira",    label_en: "Badr",               label_ar: "بدر" },
    { value: "wadi_natroun",    label_en: "Wadi El Natroun",    label_ar: "وادي النطرون" },
    { value: "nubariah",        label_en: "Nubariah",           label_ar: "النوبارية" },
  ],
  kafr_sheikh: [
    { value: "kafr_sheikh_city", label_en: "Kafr El Sheikh",    label_ar: "كفر الشيخ" },
    { value: "desouk",          label_en: "Desouk",             label_ar: "دسوق" },
    { value: "fouh",            label_en: "Fouh",               label_ar: "فوه" },
    { value: "metoubas",        label_en: "Metoubas",           label_ar: "مطوبس" },
    { value: "biyala",          label_en: "Biyala",             label_ar: "بيلا" },
    { value: "sidi_salem",      label_en: "Sidi Salem",         label_ar: "سيدي سالم" },
    { value: "qellin",          label_en: "Qellin",             label_ar: "قلين" },
    { value: "hamoul",          label_en: "Hamoul",             label_ar: "الحامول" },
    { value: "borollos",        label_en: "Borollos",           label_ar: "البرلس" },
  ],
  damietta: [
    { value: "damietta_city",   label_en: "Damietta",           label_ar: "دمياط" },
    { value: "new_damietta",    label_en: "New Damietta",       label_ar: "دمياط الجديدة" },
    { value: "ras_el_bar",      label_en: "Ras El Bar",         label_ar: "رأس البر" },
    { value: "faraskour",       label_en: "Faraskour",          label_ar: "فارسكور" },
    { value: "zarqa",           label_en: "Zarqa",              label_ar: "الزرقا" },
    { value: "kafr_saad",       label_en: "Kafr Saad",          label_ar: "كفر سعد" },
    { value: "kafr_battikh",    label_en: "Kafr El Battikh",    label_ar: "كفر البطيخ" },
    { value: "rawda",           label_en: "El Rawda",           label_ar: "الروضة" },
  ],
  port_said: [
    { value: "port_said_city",  label_en: "Port Said",          label_ar: "بورسعيد" },
    { value: "port_fouad",      label_en: "Port Fouad",         label_ar: "بورفؤاد" },
    { value: "el_arab",         label_en: "El Arab",            label_ar: "العرب" },
    { value: "el_dawahy",       label_en: "El Dawahy",          label_ar: "الضواحي" },
    { value: "el_manakh",       label_en: "El Manakh",          label_ar: "المناخ" },
    { value: "el_sharq",        label_en: "El Sharq",           label_ar: "الشرق" },
    { value: "el_zohour",       label_en: "El Zohour",          label_ar: "الزهور" },
  ],
  ismailia: [
    { value: "ismailia_city",   label_en: "Ismailia",           label_ar: "الإسماعيلية" },
    { value: "fayed",           label_en: "Fayed",              label_ar: "فايد" },
    { value: "kantara_sharq",   label_en: "Kantara Sharq",      label_ar: "القنطرة شرق" },
    { value: "kantara_gharb",   label_en: "Kantara Gharb",      label_ar: "القنطرة غرب" },
    { value: "tal_kabeer",      label_en: "Tal El Kabeer",      label_ar: "التل الكبير" },
    { value: "qassasin",        label_en: "Qassasin",           label_ar: "القصاصين" },
    { value: "abou_sweir",      label_en: "Abou Sweir",         label_ar: "أبو صوير" },
  ],
  suez: [
    { value: "suez_city",       label_en: "Suez",               label_ar: "السويس" },
    { value: "arbaeen",         label_en: "Arbaeen",            label_ar: "الأربعين" },
    { value: "ataqah",          label_en: "Ataqah",             label_ar: "عتاقة" },
    { value: "ganayen",         label_en: "Ganayen",            label_ar: "الجناين" },
    { value: "faisal_suez",     label_en: "Faisal",             label_ar: "فيصل" },
  ],
  fayoum: [
    { value: "fayoum_city",     label_en: "Fayoum",             label_ar: "الفيوم" },
    { value: "ibshawai",        label_en: "Ibshawai",           label_ar: "إبشواي" },
    { value: "yusuf_sadiq",     label_en: "Yusuf El Sadiq",     label_ar: "يوسف الصديق" },
    { value: "snoures",         label_en: "Snoures",            label_ar: "سنورس" },
    { value: "tamiyah",         label_en: "Tamiyah",            label_ar: "طامية" },
    { value: "etsa",            label_en: "Etsa",               label_ar: "إطسا" },
  ],
  beni_suef: [
    { value: "beni_suef_city",  label_en: "Beni Suef",          label_ar: "بني سويف" },
    { value: "biba",            label_en: "Biba",               label_ar: "ببا" },
    { value: "el_wasta",        label_en: "El Wasta",           label_ar: "الواسطى" },
    { value: "naser",           label_en: "Naser",              label_ar: "ناصر" },
    { value: "ehnasia",         label_en: "Ehnasia",            label_ar: "إهناسيا" },
    { value: "fashn",           label_en: "Fashn",              label_ar: "الفشن" },
    { value: "samasta",         label_en: "Samasta",            label_ar: "سمسطا" },
  ],
  minya: [
    { value: "minya_city",      label_en: "Minya",              label_ar: "المنيا" },
    { value: "new_minya",       label_en: "New Minya",          label_ar: "المنيا الجديدة" },
    { value: "mallawi",         label_en: "Mallawi",            label_ar: "ملوي" },
    { value: "abou_qurqas",     label_en: "Abou Qurqas",        label_ar: "أبو قرقاص" },
    { value: "samalut",         label_en: "Samalut",            label_ar: "سمالوط" },
    { value: "matay",           label_en: "Matay",              label_ar: "مطاي" },
    { value: "beni_mazar",      label_en: "Beni Mazar",         label_ar: "بني مزار" },
    { value: "maghagha",        label_en: "Maghagha",           label_ar: "مغاغة" },
    { value: "deir_mawas",      label_en: "Deir Mawas",         label_ar: "دير مواس" },
  ],
  assiut: [
    { value: "assiut_city",     label_en: "Assiut",             label_ar: "أسيوط" },
    { value: "new_assiut",      label_en: "New Assiut",         label_ar: "أسيوط الجديدة" },
    { value: "dayrout",         label_en: "Dayrout",            label_ar: "ديروط" },
    { value: "manfalut",        label_en: "Manfalut",           label_ar: "منفلوط" },
    { value: "qusiya",          label_en: "Qusiya",             label_ar: "القوصية" },
    { value: "abnub",           label_en: "Abnub",              label_ar: "أبنوب" },
    { value: "abu_tig",         label_en: "Abu Tig",            label_ar: "أبو تيج" },
    { value: "el_ghanaim",      label_en: "El Ghanaim",         label_ar: "الغنايم" },
    { value: "sahel_selim",     label_en: "Sahel Selim",        label_ar: "ساحل سليم" },
    { value: "el_badari",       label_en: "El Badari",          label_ar: "البداري" },
    { value: "sadfa",           label_en: "Sadfa",              label_ar: "صدفا" },
  ],
  sohag: [
    { value: "sohag_city",      label_en: "Sohag",              label_ar: "سوهاج" },
    { value: "akhmim",          label_en: "Akhmim",             label_ar: "أخميم" },
    { value: "girga",           label_en: "Girga",              label_ar: "جرجا" },
    { value: "tama",            label_en: "Tama",               label_ar: "طما" },
    { value: "tahta",           label_en: "Tahta",              label_ar: "طهطا" },
    { value: "el_maragha",      label_en: "El Maragha",         label_ar: "المراغة" },
    { value: "el_balyana",      label_en: "El Balyana",         label_ar: "البلينا" },
    { value: "dar_el_salam",    label_en: "Dar El Salam",       label_ar: "دار السلام" },
    { value: "el_monshah",      label_en: "El Monshah",         label_ar: "المنشاة" },
    { value: "saqulta",         label_en: "Saqulta",            label_ar: "ساقلتة" },
  ],
  qena: [
    { value: "qena_city",       label_en: "Qena",               label_ar: "قنا" },
    { value: "new_qena",        label_en: "New Qena",           label_ar: "قنا الجديدة" },
    { value: "naqada",          label_en: "Naqada",             label_ar: "نقادة" },
    { value: "qus",             label_en: "Qus",                label_ar: "قوص" },
    { value: "abou_tesht",      label_en: "Abou Tesht",         label_ar: "أبو تشت" },
    { value: "farshout",        label_en: "Farshout",           label_ar: "فرشوط" },
    { value: "nag_hammadi",     label_en: "Nag Hammadi",        label_ar: "نجع حمادي" },
    { value: "deshna",          label_en: "Deshna",             label_ar: "دشنا" },
  ],
  luxor: [
    { value: "luxor_city",      label_en: "Luxor",              label_ar: "الأقصر" },
    { value: "new_luxor",       label_en: "New Luxor",          label_ar: "الأقصر الجديدة" },
    { value: "esna",            label_en: "Esna",               label_ar: "إسنا" },
    { value: "armant",          label_en: "Armant",             label_ar: "أرمنت" },
    { value: "tod",             label_en: "El Tod",             label_ar: "الطود" },
    { value: "el_zaynia",       label_en: "El Zaynia",          label_ar: "الزينية" },
    { value: "el_bayadiyah",    label_en: "El Bayadiyah",       label_ar: "البياضية" },
  ],
  aswan: [
    { value: "aswan_city",      label_en: "Aswan",              label_ar: "أسوان" },
    { value: "new_aswan",       label_en: "New Aswan",          label_ar: "أسوان الجديدة" },
    { value: "kom_ombo",        label_en: "Kom Ombo",           label_ar: "كوم أمبو" },
    { value: "draw",            label_en: "Draw",               label_ar: "دراو" },
    { value: "edfu",            label_en: "Edfu",               label_ar: "إدفو" },
    { value: "nasr_nuba",       label_en: "Nasr El Nuba",       label_ar: "نصر النوبة" },
    { value: "kalabsha",        label_en: "Kalabsha",           label_ar: "كلابشة" },
    { value: "abu_simbel",      label_en: "Abu Simbel",         label_ar: "أبو سمبل" },
  ],
  red_sea: [
    { value: "hurghada",        label_en: "Hurghada",           label_ar: "الغردقة" },
    { value: "ras_ghareb",      label_en: "Ras Ghareb",         label_ar: "رأس غارب" },
    { value: "safaga",          label_en: "Safaga",             label_ar: "سفاجا" },
    { value: "qoseir",          label_en: "Qoseir",             label_ar: "القصير" },
    { value: "marsa_alam",      label_en: "Marsa Alam",         label_ar: "مرسى علم" },
    { value: "shalateen",       label_en: "Shalateen",          label_ar: "شلاتين" },
    { value: "halayeb",         label_en: "Halayeb",            label_ar: "حلايب" },
  ],
  new_valley: [
    { value: "kharga",          label_en: "Kharga",             label_ar: "الخارجة" },
    { value: "dakhla",          label_en: "Dakhla",             label_ar: "الداخلة" },
    { value: "farafra",         label_en: "Farafra",            label_ar: "الفرافرة" },
    { value: "balat",           label_en: "Balat",              label_ar: "بلاط" },
    { value: "paris",           label_en: "Paris",              label_ar: "باريس" },
  ],
  matrouh: [
    { value: "marsa_matrouh",   label_en: "Marsa Matrouh",      label_ar: "مرسى مطروح" },
    { value: "alamein",         label_en: "El Alamein",         label_ar: "العلمين" },
    { value: "dabaa",           label_en: "El Dabaa",           label_ar: "الضبعة" },
    { value: "siwa",            label_en: "Siwa",               label_ar: "سيوة" },
    { value: "sallum",          label_en: "Sallum",             label_ar: "السلوم" },
    { value: "barani",          label_en: "Sidi Barani",        label_ar: "سيدي براني" },
    { value: "hamam",           label_en: "El Hamam",           label_ar: "الحمام" },
    { value: "negila",          label_en: "Negila",             label_ar: "النجيلة" },
  ],
  north_sinai: [
    { value: "arish",           label_en: "Arish",              label_ar: "العريش" },
    { value: "sheikh_zuwayid",  label_en: "Sheikh Zuwayid",     label_ar: "الشيخ زويد" },
    { value: "rafah",           label_en: "Rafah",              label_ar: "رفح" },
    { value: "bir_abd",         label_en: "Bir El Abd",         label_ar: "بئر العبد" },
    { value: "hasana",          label_en: "El Hasana",          label_ar: "الحسنة" },
    { value: "nakhl",           label_en: "Nakhl",              label_ar: "نخل" },
  ],
  south_sinai: [
    { value: "tor_sinai",       label_en: "Tor Sinai",          label_ar: "طور سيناء" },
    { value: "sharm_el_sheikh", label_en: "Sharm El Sheikh",    label_ar: "شرم الشيخ" },
    { value: "dahab",           label_en: "Dahab",              label_ar: "دهب" },
    { value: "nuweiba",         label_en: "Nuweiba",            label_ar: "نويبع" },
    { value: "taba",            label_en: "Taba",               label_ar: "طابا" },
    { value: "saint_catherine", label_en: "Saint Catherine",    label_ar: "سانت كاترين" },
    { value: "abu_zenima",      label_en: "Abu Zenima",         label_ar: "أبو زنيمة" },
    { value: "abu_redis",       label_en: "Abu Redis",          label_ar: "أبو رديس" },
            { value: "ras_sidr",        label_en: "Ras Sidr",           label_ar: "رأس سدر" },
  ],
  outside_egypt: [
    { value: "other", label_en: "Other (specify in cover letter)", label_ar: "أخرى (حدد في الخطاب التعريفي)" },
  ],
};

export function getCitiesForGovernorate(govKey: string | undefined | null): CityOption[] {
  if (!govKey) return [];
  return EGYPT_CITIES[govKey] || [];
}
