project_id = "lrouvlmandrjughswbyw"

[functions.create-user]
verify_jwt = false

[functions.generate-sessions]
verify_jwt = false

[functions.session-reminders]
verify_jwt = false

[functions.delete-users]
verify_jwt = false

[functions.grade-quiz]
verify_jwt = false
