
-- Fix scheduled sessions that have stale content_number <= last_delivered_content_number
-- These were generated by the old trigger before the fix
UPDATE sessions s
SET content_number = g.last_delivered_content_number + 1
FROM groups g
WHERE s.group_id = g.id
  AND s.is_makeup IS NOT TRUE
  AND s.status = 'scheduled'
  AND s.content_number IS NOT NULL
  AND s.content_number <= g.last_delivered_content_number
  AND g.is_active = true;
