
INSERT INTO public.email_templates (name, audience, subject_en, subject_ar, body_html_en, body_html_ar, subject_telegram_en, subject_telegram_ar, body_telegram_md_en, body_telegram_md_ar, is_active, description)
VALUES
  ('admin-payment-recorded','admin','💰 Payment recorded','💰 تم تسجيل دفعة',
   '<p>Payment of {{amount}} EGP from {{studentName}}</p>','<p>دفعة بقيمة {{amount}} ج.م من {{studentName}}</p>',
   '💰 Payment recorded','💰 دفعة جديدة',
   '💰 *Payment recorded*\n\n👤 Student: *{{studentName}}*\n💵 Amount: *{{amount}} EGP*\n💳 Method: {{method}}\n👨‍💼 By: {{recordedBy}}',
   '💰 *تم تسجيل دفعة جديدة*\n\n👤 الطالب: *{{studentName}}*\n💵 المبلغ: *{{amount}} ج.م*\n💳 الطريقة: {{method}}\n👨‍💼 بواسطة: {{recordedBy}}',
   true, 'Admin alert when payment recorded'),

  ('admin-expense-recorded','admin','💸 Expense recorded','💸 تم تسجيل مصروف',
   '<p>{{category}}: {{amount}} EGP</p>','<p>{{category}}: {{amount}} ج.م</p>',
   '💸 Expense','💸 مصروف',
   '💸 *Expense recorded*\n\n📂 Category: *{{category}}*\n💵 Amount: *{{amount}} EGP*\n📝 {{description}}\n👨‍💼 By: {{recordedBy}}',
   '💸 *تم تسجيل مصروف*\n\n📂 الفئة: *{{category}}*\n💵 المبلغ: *{{amount}} ج.م*\n📝 {{description}}\n👨‍💼 بواسطة: {{recordedBy}}',
   true, 'Admin alert when expense recorded'),

  ('admin-salary-paid','admin','💼 Salary paid','💼 صرف راتب',
   '<p>Salary of {{amount}} EGP paid to {{employeeName}}</p>','<p>صرف راتب {{amount}} ج.م لـ {{employeeName}}</p>',
   '💼 Salary paid','💼 صرف راتب',
   '💼 *Salary paid*\n\n👤 Employee: *{{employeeName}}*\n💵 Amount: *{{amount}} EGP*\n📅 Month: {{month}}',
   '💼 *تم صرف راتب*\n\n👤 الموظف: *{{employeeName}}*\n💵 المبلغ: *{{amount}} ج.م*\n📅 الشهر: {{month}}',
   true, 'Admin alert on salary payment'),

  ('admin-treasury-transfer','admin','🏦 Treasury transfer','🏦 تحويل خزينة',
   '<p>Transfer of {{amount}} EGP</p>','<p>تحويل {{amount}} ج.م</p>',
   '🏦 Transfer','🏦 تحويل',
   '🏦 *Treasury transfer*\n\n📤 From: *{{fromAccount}}*\n📥 To: *{{toAccount}}*\n💵 Amount: *{{amount}} EGP*',
   '🏦 *تحويل بين الخزن*\n\n📤 من: *{{fromAccount}}*\n📥 إلى: *{{toAccount}}*\n💵 المبلغ: *{{amount}} ج.م*',
   true, 'Admin alert on treasury transfer'),

  ('admin-student-created','admin','👤 New student','👤 طالب جديد',
   '<p>New student: {{studentName}}</p>','<p>طالب جديد: {{studentName}}</p>',
   '👤 New student','👤 طالب جديد',
   '👤 *New student created*\n\n📝 Name: *{{studentName}}*\n📞 Phone: {{phone}}\n👨‍💼 By: {{createdBy}}',
   '👤 *تم إضافة طالب جديد*\n\n📝 الاسم: *{{studentName}}*\n📞 الهاتف: {{phone}}\n👨‍💼 بواسطة: {{createdBy}}',
   true, 'Admin alert on new student'),

  ('admin-student-deleted','admin','🗑️ Student deleted','🗑️ حذف طالب',
   '<p>Student {{studentName}} deleted</p>','<p>تم حذف الطالب {{studentName}}</p>',
   '🗑️ Deleted','🗑️ حذف',
   '🗑️ *Student deleted*\n\n👤 Name: *{{studentName}}*\n👨‍💼 By: {{deletedBy}}',
   '🗑️ *تم حذف طالب*\n\n👤 الاسم: *{{studentName}}*\n👨‍💼 بواسطة: {{deletedBy}}',
   true, 'Admin alert on student deletion'),

  ('admin-subscription-renewed','admin','🔄 Subscription renewed','🔄 تجديد اشتراك',
   '<p>{{studentName}} renewed</p>','<p>{{studentName}} جدد الاشتراك</p>',
   '🔄 Renewed','🔄 تجديد',
   '🔄 *Subscription renewed*\n\n👤 Student: *{{studentName}}*\n📚 Level: {{levelName}}\n💵 Amount: {{amount}} EGP',
   '🔄 *تم تجديد اشتراك*\n\n👤 الطالب: *{{studentName}}*\n📚 المستوى: {{levelName}}\n💵 المبلغ: {{amount}} ج.م',
   true, 'Admin alert on subscription renewal'),

  ('admin-student-transferred','admin','🔀 Student transferred','🔀 نقل طالب',
   '<p>{{studentName}} moved</p>','<p>تم نقل {{studentName}}</p>',
   '🔀 Transfer','🔀 نقل',
   '🔀 *Student transferred*\n\n👤 *{{studentName}}*\n📤 From: {{fromGroup}}\n📥 To: {{toGroup}}',
   '🔀 *تم نقل طالب*\n\n👤 *{{studentName}}*\n📤 من: {{fromGroup}}\n📥 إلى: {{toGroup}}',
   true, 'Admin alert on student transfer'),

  ('admin-parent-approved','admin','✅ Parent approved','✅ موافقة ولي أمر',
   '<p>{{parentName}} approved</p>','<p>تمت الموافقة على {{parentName}}</p>',
   '✅ Approved','✅ موافقة',
   '✅ *Parent account approved*\n\n👤 Parent: *{{parentName}}*\n👨‍💼 By: {{approvedBy}}',
   '✅ *تمت الموافقة على ولي أمر*\n\n👤 ولي الأمر: *{{parentName}}*\n👨‍💼 بواسطة: {{approvedBy}}',
   true, 'Admin alert on parent approval'),

  ('admin-parent-linked','admin','🔗 Parent linked','🔗 ربط ولي أمر',
   '<p>{{parentName}} linked to {{studentName}}</p>','<p>تم ربط {{parentName}} بـ {{studentName}}</p>',
   '🔗 Linked','🔗 ربط',
   '🔗 *Parent linked to student*\n\n👨‍👩 Parent: *{{parentName}}*\n👤 Student: *{{studentName}}*',
   '🔗 *تم ربط ولي أمر بطالب*\n\n👨‍👩 ولي الأمر: *{{parentName}}*\n👤 الطالب: *{{studentName}}*',
   true, 'Admin alert on parent-student link'),

  ('admin-parent-registered','admin','📝 New parent registration','📝 تسجيل ولي أمر',
   '<p>{{parentName}} registered</p>','<p>{{parentName}} سجل</p>',
   '📝 New parent','📝 ولي أمر',
   '📝 *New parent registration*\n\n👤 Name: *{{parentName}}*\n📧 Email: {{email}}\n\n⚠️ _Awaiting approval_',
   '📝 *تسجيل ولي أمر جديد*\n\n👤 الاسم: *{{parentName}}*\n📧 الإيميل: {{email}}\n\n⚠️ _في انتظار الموافقة_',
   true, 'Admin alert on new parent registration'),

  ('admin-certificate-issued','admin','🏆 Certificate issued','🏆 إصدار شهادة',
   '<p>Certificate for {{studentName}}</p>','<p>شهادة لـ {{studentName}}</p>',
   '🏆 Certificate','🏆 شهادة',
   '🏆 *Certificate issued*\n\n👤 Student: *{{studentName}}*\n📚 Level: *{{levelName}}*',
   '🏆 *تم إصدار شهادة*\n\n👤 الطالب: *{{studentName}}*\n📚 المستوى: *{{levelName}}*',
   true, 'Admin alert on certificate issuance'),

  ('admin-level-completed','admin','🎓 Level completed','🎓 اكتمال مستوى',
   '<p>{{studentName}} completed {{levelName}}</p>','<p>{{studentName}} أكمل {{levelName}}</p>',
   '🎓 Level done','🎓 اكتمال',
   '🎓 *Student completed level*\n\n👤 Student: *{{studentName}}*\n📚 Level: *{{levelName}}*\n📊 Score: {{score}}',
   '🎓 *طالب أكمل مستوى*\n\n👤 الطالب: *{{studentName}}*\n📚 المستوى: *{{levelName}}*\n📊 الدرجة: {{score}}',
   true, 'Admin alert on level completion'),

  ('admin-makeup-created','admin','📅 Makeup session','📅 جلسة تعويضية',
   '<p>Makeup for {{studentName}}</p>','<p>تعويضية لـ {{studentName}}</p>',
   '📅 Makeup','📅 تعويضية',
   '📅 *Makeup session created*\n\n👤 Student: *{{studentName}}*\n📆 Original: {{originalDate}}\n📆 Makeup: *{{makeupDate}}*',
   '📅 *تم إنشاء جلسة تعويضية*\n\n👤 الطالب: *{{studentName}}*\n📆 الأصلية: {{originalDate}}\n📆 التعويضية: *{{makeupDate}}*',
   true, 'Admin alert on makeup creation'),

  ('admin-leave-requested','admin','🌴 Leave request','🌴 طلب إجازة',
   '<p>{{studentName}} requested leave</p>','<p>{{studentName}} طلب إجازة</p>',
   '🌴 Leave','🌴 إجازة',
   '🌴 *New leave request*\n\n👤 Student: *{{studentName}}*\n📆 From: {{fromDate}}\n📆 To: {{toDate}}\n📝 Reason: {{reason}}',
   '🌴 *طلب إجازة جديد*\n\n👤 الطالب: *{{studentName}}*\n📆 من: {{fromDate}}\n📆 إلى: {{toDate}}\n📝 السبب: {{reason}}',
   true, 'Admin alert on leave request'),

  ('admin-subscription-request','admin','📩 Subscription inquiry','📩 طلب اشتراك',
   '<p>{{name}} inquired</p>','<p>{{name}} استفسر</p>',
   '📩 Inquiry','📩 استفسار',
   '📩 *New subscription inquiry*\n\n👤 Name: *{{name}}*\n📞 Phone: {{phone}}\n📦 Plan: {{plan}}',
   '📩 *طلب اشتراك جديد*\n\n👤 الاسم: *{{name}}*\n📞 الهاتف: {{phone}}\n📦 الباقة: {{plan}}',
   true, 'Admin alert on subscription inquiry'),

  ('admin-employee-warning','admin','⚠️ Employee warning','⚠️ إنذار موظف',
   '<p>Warning for {{employeeName}}</p>','<p>إنذار لـ {{employeeName}}</p>',
   '⚠️ Warning','⚠️ إنذار',
   '⚠️ *Employee warning issued*\n\n👤 Employee: *{{employeeName}}*\n📝 Reason: {{reason}}\n👨‍💼 By: {{issuedBy}}',
   '⚠️ *تم إصدار إنذار لموظف*\n\n👤 الموظف: *{{employeeName}}*\n📝 السبب: {{reason}}\n👨‍💼 بواسطة: {{issuedBy}}',
   true, 'Admin alert on employee warning'),

  ('admin-group-created','admin','👥 New group','👥 مجموعة جديدة',
   '<p>Group {{groupName}} created</p>','<p>تم إنشاء {{groupName}}</p>',
   '👥 Group','👥 مجموعة',
   '👥 *New group created*\n\n📛 Name: *{{groupName}}*\n📚 Level: {{levelName}}\n👨‍💼 By: {{createdBy}}',
   '👥 *تم إنشاء مجموعة جديدة*\n\n📛 الاسم: *{{groupName}}*\n📚 المستوى: {{levelName}}\n👨‍💼 بواسطة: {{createdBy}}',
   true, 'Admin alert on group creation')
ON CONFLICT (name) DO NOTHING;
