-- Add missing variables to email_event_catalog so templates can use them without warnings
UPDATE email_event_catalog SET available_variables = '[{"key": "instructorName", "label_ar": "اسم المدرب", "label_en": "Instructor name"}, {"key": "sessionDate", "label_ar": "تاريخ السيشن", "label_en": "Session date"}, {"key": "note", "label_ar": "الملاحظة", "label_en": "Note"}, {"key": "feedback", "label_en": "Feedback", "label_ar": "الملاحظة", "sample": "Great work this week"}, {"key": "groupName", "label_en": "Group Name", "label_ar": "اسم المجموعة", "sample": "Group A"}]'::jsonb WHERE event_key = 'instructor-admin-note';

UPDATE email_event_catalog SET available_variables = '[{"key": "instructorName", "label_ar": "اسم المدرب", "label_en": "Instructor name"}, {"key": "itemTitle", "label_ar": "العنوان", "label_en": "Item title"}, {"key": "ungradedCount", "label_ar": "عدد بدون تصحيح", "label_en": "Ungraded count"}, {"key": "deadline", "label_ar": "الميعاد", "label_en": "Deadline"}, {"key": "hoursLeft", "label_en": "Hours Left", "label_ar": "الساعات المتبقية", "type": "number", "sample": "24"}, {"key": "title", "label_en": "Title", "label_ar": "العنوان", "sample": "Quiz 1"}]'::jsonb WHERE event_key = 'instructor-deadline-approaching';

UPDATE email_event_catalog SET available_variables = '[{"key": "instructorName", "label_ar": "اسم المدرب", "label_en": "Instructor name"}, {"key": "itemTitle", "label_ar": "العنوان", "label_en": "Item title"}, {"key": "daysOverdue", "label_ar": "أيام التأخير", "label_en": "Days overdue"}, {"key": "breachHours", "label_en": "Breach Hours", "label_ar": "ساعات التأخير", "type": "number", "sample": "48"}, {"key": "pendingCount", "label_en": "Pending Count", "label_ar": "عدد المعلق", "type": "number", "sample": "5"}, {"key": "quizTitle", "label_en": "Quiz Title", "label_ar": "عنوان الكويز", "sample": "Final Exam"}]'::jsonb WHERE event_key = 'instructor-grading-late';

UPDATE email_event_catalog SET available_variables = '[{"key": "instructorName", "label_ar": "اسم المدرب", "label_en": "Instructor name"}, {"key": "groupName", "label_ar": "اسم المجموعة", "label_en": "Group name"}, {"key": "absenceRate", "label_ar": "نسبة الغياب", "label_en": "Absence rate"}, {"key": "period", "label_en": "Period", "label_ar": "الفترة", "sample": "Last 30 days"}]'::jsonb WHERE event_key = 'instructor-high-absence-rate';

UPDATE email_event_catalog SET available_variables = '[{"key": "instructorName", "label_ar": "اسم المدرب", "label_en": "Instructor name"}, {"key": "avgRating", "label_ar": "متوسط التقييم", "label_en": "Avg rating"}, {"key": "period", "label_ar": "الفترة", "label_en": "Period"}, {"key": "groupName", "label_en": "Group Name", "label_ar": "اسم المجموعة", "sample": "Group A"}, {"key": "rating", "label_en": "Rating", "label_ar": "التقييم", "type": "number", "sample": "2.5"}, {"key": "sessionDate", "label_en": "Session Date", "label_ar": "تاريخ الحصة", "type": "date", "sample": "2025-01-15"}]'::jsonb WHERE event_key = 'instructor-low-rating';

UPDATE email_event_catalog SET available_variables = '[{"key": "instructorName", "label_ar": "اسم المدرب", "label_en": "Instructor name"}, {"key": "newSchedule", "label_ar": "الجدول الجديد", "label_en": "New schedule"}, {"key": "groupName", "label_en": "Group Name", "label_ar": "اسم المجموعة", "sample": "Group A"}, {"key": "newSlot", "label_en": "New Slot", "label_ar": "الموعد الجديد", "sample": "Mon 5pm"}, {"key": "oldSlot", "label_en": "Old Slot", "label_ar": "الموعد القديم", "sample": "Sun 6pm"}]'::jsonb WHERE event_key = 'instructor-schedule-changed';

UPDATE email_event_catalog SET available_variables = '[{"key": "instructorName", "label_ar": "اسم المدرب", "label_en": "Instructor name"}, {"key": "groupName", "label_ar": "اسم المجموعة", "label_en": "Group name"}, {"key": "originalDate", "label_ar": "التاريخ الأصلي", "label_en": "Original date"}, {"key": "reason", "label_ar": "السبب", "label_en": "Reason"}, {"key": "action", "label_en": "Action", "label_ar": "الإجراء", "sample": "Rescheduled"}, {"key": "sessionDate", "label_en": "Session Date", "label_ar": "تاريخ الحصة", "type": "date", "sample": "2025-01-15"}]'::jsonb WHERE event_key = 'instructor-session-cancelled';

UPDATE email_event_catalog SET available_variables = '[{"key": "instructorName", "label_ar": "اسم المدرب", "label_en": "Instructor name"}, {"key": "warningType", "label_ar": "نوع الإنذار", "label_en": "Warning type"}, {"key": "reason", "label_ar": "السبب", "label_en": "Reason"}, {"key": "warningDetails", "label_en": "Warning Details", "label_ar": "تفاصيل الإنذار", "sample": "Repeated lateness"}, {"key": "warningTitle", "label_en": "Warning Title", "label_ar": "عنوان الإنذار", "sample": "Attendance Warning"}]'::jsonb WHERE event_key = 'instructor-warning-issued';

UPDATE email_event_catalog SET available_variables = '[{"key": "accountId", "label_ar": "معرف الحساب", "label_en": "Account ID"}, {"key": "accountType", "label_ar": "نوع الحساب", "label_en": "Account type"}, {"key": "difference", "label_ar": "الفرق", "label_en": "Difference"}, {"key": "cached", "label_en": "Cached Balance", "label_ar": "الرصيد المخزن", "type": "number", "sample": "1000"}, {"key": "computed", "label_en": "Computed Balance", "label_ar": "الرصيد المحسوب", "type": "number", "sample": "950"}, {"key": "diff", "label_en": "Difference (alias)", "label_ar": "الفرق", "type": "number", "sample": "50"}]'::jsonb WHERE event_key = 'staff-balance-mismatch';

UPDATE email_event_catalog SET available_variables = '[{"key": "date", "label_ar": "التاريخ", "label_en": "Date"}, {"key": "sessionsCount", "label_ar": "عدد السيشنات", "label_en": "Sessions count"}, {"key": "newPayments", "label_ar": "المدفوعات الجديدة", "label_en": "New payments"}, {"key": "attendanceRate", "label_ar": "نسبة الحضور", "label_en": "Attendance rate"}, {"key": "paymentsTotal", "label_en": "Payments Total", "label_ar": "إجمالي المدفوعات", "type": "number", "sample": "5000"}]'::jsonb WHERE event_key = 'staff-daily-summary';

UPDATE email_event_catalog SET available_variables = '[{"key": "studentName", "label_ar": "اسم الطالب", "label_en": "Student name"}, {"key": "phone", "label_ar": "الهاتف", "label_en": "Phone"}, {"key": "plan", "label_ar": "الباقة", "label_en": "Plan"}, {"key": "planName", "label_en": "Plan Name (alias)", "label_ar": "اسم الباقة", "sample": "3-month"}]'::jsonb WHERE event_key = 'staff-new-subscription-request';